// <auto-generated />
using System;
using BattleHub.Infraestrutura.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029050307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BattleHub.Domain.Entities.Inscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TorneioId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("Inscricoes", (string)null);
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Participantes", (string)null);
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AgendadaPara")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParticipanteAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParticipanteBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rodada")
                        .HasColumnType("int");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TorneioId", "Rodada");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Torneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Torneios", (string)null);
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("BattleHub.Domain.Entities.Torneio", null)
                        .WithMany("Inscricoes")
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Participante", b =>
                {
                    b.OwnsOne("BattleHub.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("ParticipanteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Nome");

                            b1.HasKey("ParticipanteId");

                            b1.ToTable("Participantes");

                            b1.WithOwner()
                                .HasForeignKey("ParticipanteId");
                        });

                    b.OwnsOne("BattleHub.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ParticipanteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("nvarchar(180)")
                                .HasColumnName("Email");

                            b1.HasKey("ParticipanteId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Participantes");

                            b1.WithOwner()
                                .HasForeignKey("ParticipanteId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Partida", b =>
                {
                    b.HasOne("BattleHub.Domain.Entities.Torneio", null)
                        .WithMany("Partidas")
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BattleHub.Domain.ValueObjects.ResultadoPartida", "Resultado", b1 =>
                        {
                            b1.Property<Guid>("PartidaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Placar")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Placar");

                            b1.Property<Guid>("VencedorId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("VencedorId");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Torneio", b =>
                {
                    b.OwnsOne("BattleHub.Domain.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("TorneioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Nome");

                            b1.HasKey("TorneioId");

                            b1.HasIndex("Valor");

                            b1.ToTable("Torneios");

                            b1.WithOwner()
                                .HasForeignKey("TorneioId");
                        });

                    b.OwnsOne("BattleHub.Domain.ValueObjects.PeriodoDatas", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("TorneioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Fim")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataFim");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataInicio");

                            b1.HasKey("TorneioId");

                            b1.ToTable("Torneios");

                            b1.WithOwner()
                                .HasForeignKey("TorneioId");
                        });

                    b.OwnsOne("BattleHub.Domain.ValueObjects.TamanhoChave", "TamanhoChave", b1 =>
                        {
                            b1.Property<Guid>("TorneioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("TamanhoChave");

                            b1.HasKey("TorneioId");

                            b1.ToTable("Torneios");

                            b1.WithOwner()
                                .HasForeignKey("TorneioId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Periodo")
                        .IsRequired();

                    b.Navigation("TamanhoChave")
                        .IsRequired();
                });

            modelBuilder.Entity("BattleHub.Domain.Entities.Torneio", b =>
                {
                    b.Navigation("Inscricoes");

                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
